# Welcome to Jekyll!

# Website settings
title: arpit
description: arpit's personal website
keywords: arpit, arpit1997, arpitsolanki, arpitsolanki1997
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage'
url: http://jarrekk.github.io/Jalpc  # url should be changed to 'http://www.jack003.com/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be changed to '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author: # change following line to your infomation.
  name: Arpit Solanki # Be used at blog posts' author.
  first_name: arpit  # Be used at index page about me section.
  last_name: solanki  # Be used at index page about me section.
  email: solankiarpit1997@gmail.com  # Leave blank if you don't have now
  facebook_username: arpit.solanki.97  # Leave blank if you don't have now
  github_username: arpit1997  # Leave blank if you don't have now
  twitter_username: solankiarpit191
  linkedin_username: arpit-solanki
  stackoverflow_username: 5250746/arpit-solanki
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Another Web Developer


# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
